{
 "title": "Mix Dashboards",
 "time": { "from": "2021-05-31T13:31:56.803Z", "to": "2021-05-31T16:21:47.644Z" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "200",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "rawSql": "select count(\"Status\") as \"Успешно\"\nfrom responses\nwhere \"Status\"=200",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "400",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "rawSql": "select count(\"Status\") as \"Ошибка клиента\"\nfrom responses\nwhere \"Status\"=400",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "500",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "rawSql": "select count(\"Status\") as \"Ошибка программы\"\nfrom responses\nwhere \"Status\"=500",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  { "title": "Dash3", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Stat OverAll",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"Status\", count(\"Status\")\nFROM public.responses\nGroup by \"Status\""
    }
   ]
  },
  {
   "title": "Stat Pie OverAll",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(\"Status\") as \"Status 200\"\nFROM public.responses\nwhere \"Status\"=200\nGroup by \"Status\"\n"
    },
    {
     "rawSql": "SELECT count(\"Status\") as \"Status 400\"\nFROM public.responses\nwhere \"Status\"=400\nGroup by \"Status\"\n"
    },
    {
     "rawSql": "SELECT count(\"Status\") as \"Status 500\"\nFROM public.responses\nwhere \"Status\"=500\nGroup by \"Status\""
    }
   ]
  },
  {
   "title": "Statusmap OverAll",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "rawSql": "SELECT\n  $__timeGroupAlias(\"Start\",80s),\n  \"Strategy\" AS metric,\n  min(\"Status\") AS \"Status\"\nFROM responses\nGROUP BY 1,2\nORDER BY 1,2",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Latency OverAll",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"Start\",$__interval),\n  \"Strategy\" AS metric,\n  avg(\"Duration\") AS \"\"\"Duration\"\"\"\nFROM responses\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Latency CV_ULL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "rawSql": "SELECT\n  $__timeGroupAlias(\"Start\",$__interval),\n  avg(\"Duration\") AS \"\"\"Duration\"\"\"\nFROM responses\nWHERE\n  \"Strategy\" = 'CV_UCL'\nGROUP BY 1\nORDER BY 1",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "rawSql": "SELECT\n  $__timeGroupAlias(\"Start\",$__interval),\n  avg(\"Status\") AS \"\"\"Status\"\"\"\nFROM responses\nWHERE\n  \"Strategy\" = 'CV_UCL'\nGROUP BY 1\nORDER BY 1",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Latency CV_CC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"Start\",$__interval),\n  avg(\"Duration\") AS \"\"\"Duration\"\"\"\nFROM responses\nWHERE\n  \"Strategy\" = 'CV_CC'\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"Start\",$__interval),\n  avg(\"Status\") AS \"\"\"Status\"\"\"\nFROM responses\nWHERE\n  \"Strategy\" = 'CV_CC'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Latency SM10",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"Start\" AS \"time\",\n  \"Duration\"\nFROM responses\nWHERE\n  \"Strategy\" = 'SM10'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"Start\",$__interval),\n  avg(\"Status\") AS \"\"\"Status\"\"\"\nFROM responses\nWHERE\n  \"Strategy\" = 'SM10'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Latency SM9",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"Start\" AS \"time\",\n  \"Duration\"\nFROM responses\nWHERE\n  \"Strategy\" = 'SM9'\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"Start\",$__interval),\n  avg(\"Status\") AS \"\"\"Status\"\"\"\nFROM responses\nWHERE\n  \"Strategy\" = 'SM9'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  }
 ]
}